//! The touch-typing engine behind Tinkhaven Typing, ported from Klavaro.
//!
//! This crate is deliberately free of I/O and of any web or UI dependency: it
//! parses Klavaro's data files, generates exercises from a seed, and scores
//! keystrokes. That lets the identical code run in the browser as WebAssembly,
//! where the typing loop lives, and on the server, where results are checked
//! before they reach the leaderboard.
//!
//! # Layout of the port
//!
//! - [`kbd`] — keyboard layouts and finger assignment
//! - [`lesson`] — the 43 lessons of the Basic module
//! - [`corpus`] — word lists and paragraphs per language
//! - [`exercise`] — generating practice text, reproducibly from a seed
//! - [`typist`] — the typing loop and how the text is coloured
//! - [`stats`] — accuracy, speed and fluidness
//! - [`goals`] — the modules and the bar each one sets
//! - [`rng`] — the seeded generator the client and server share
//!
//! # Example
//!
//! ```
//! use typing_core::{exercise, goals::Module, lesson, load_layout, stats::Session};
//!
//! let layout = load_layout("qwerty_us").expect("bundled layout");
//! let lessons = lesson::klavaro_lessons();
//!
//! let exercise = exercise::generate(
//!     exercise::Request {
//!         module: Module::Basic,
//!         layout: &layout,
//!         lesson: Some(&lessons[0]),
//!         corpus: None,
//!         stop_marks: true,
//!     },
//!     0xC0FFEE,
//! )?;
//!
//! // Lesson 1 practises the two index-finger home keys.
//! assert!(exercise.text.chars().all(|c| "fj \n".contains(c)));
//!
//! // Type it perfectly, one keystroke every 150 ms.
//! let mut session = Session::new();
//! for (i, _) in exercise.text.chars().filter(|c| *c != '\n').enumerate() {
//!     session.correct((i as u64 + 1) * 150_000);
//! }
//! let score = session.score();
//! assert_eq!(score.accuracy, 100.0);
//! # Ok::<(), Box<dyn std::error::Error>>(())
//! ```

#![forbid(unsafe_code)]

pub mod corpus;
pub mod exercise;
pub mod goals;
pub mod kbd;
pub mod lesson;
pub mod rng;
pub mod stats;
pub mod typist;

use kbd::{Layout, ParseError};

// `LAYOUT_FILES`, generated by build.rs from assets/klavaro-data/layouts.
include!(concat!(env!("OUT_DIR"), "/layouts.rs"));

/// The layout offered before the visitor picks one.
pub const DEFAULT_LAYOUT: &str = "qwerty_us";

/// Languages the interface is translated into, as BCP-47 codes.
///
/// Practice corpora exist for far more languages than this; these are the ones
/// whose *interface* strings are translated. See `docs/DIVERGENCE.md`.
pub const UI_LANGUAGES: [&str; 4] = ["en", "nl", "fr", "de"];

/// The names of every bundled keyboard layout, sorted.
pub fn layout_names() -> impl Iterator<Item = &'static str> {
    LAYOUT_FILES.iter().map(|(name, _)| *name)
}

/// Parses a bundled layout by name, e.g. `azerty_be`.
///
/// Returns `None` if there is no such layout. Panics only if a *bundled* file
/// fails to parse, which would be a packaging error rather than bad input.
pub fn load_layout(name: &str) -> Option<Layout> {
    let (_, body) = LAYOUT_FILES.iter().find(|(n, _)| *n == name)?;
    Some(
        Layout::parse(name, body)
            .unwrap_or_else(|e| panic!("bundled layout {name} does not parse: {e}")),
    )
}

/// Parses every bundled layout, reporting the first that fails.
///
/// Used by the packaging test; applications want [`load_layout`].
pub fn load_all_layouts() -> Result<Vec<Layout>, ParseError> {
    LAYOUT_FILES
        .iter()
        .map(|(name, body)| Layout::parse(name, body))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_bundled_layout_parses() {
        let layouts = load_all_layouts().expect("all bundled layouts must parse");
        assert_eq!(layouts.len(), 77, "expected Klavaro 3.14's 77 layouts");
    }

    #[test]
    fn layout_names_are_sorted_and_unique() {
        let names: Vec<&str> = layout_names().collect();
        let mut sorted = names.clone();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(names, sorted, "build.rs should emit sorted, unique names");
    }

    #[test]
    fn the_default_layout_exists() {
        assert!(load_layout(DEFAULT_LAYOUT).is_some());
    }

    #[test]
    fn belgian_and_dutch_relevant_layouts_are_present() {
        for name in ["azerty_be", "qwerty_us", "qwertz_de", "azerty_fr"] {
            assert!(load_layout(name).is_some(), "missing layout {name}");
        }
    }

    #[test]
    fn unknown_layouts_are_none_not_a_panic() {
        assert!(load_layout("no_such_layout").is_none());
    }

    #[test]
    fn every_layout_can_drive_the_first_lesson() {
        // A layout with no key at the index-finger home positions would make the
        // Basic module unusable, so this is worth knowing at build time.
        let lessons = lesson::klavaro_lessons();
        let mut unusable = Vec::new();
        for layout in load_all_layouts().unwrap() {
            if lessons[0].char_set(&layout).len() < 2 {
                unusable.push(layout.name);
            }
        }
        assert!(unusable.is_empty(), "lesson 1 is unusable on: {unusable:?}");
    }
}
